doc_categories:
  doc_categories_enabled:
    default: false
    client: true
  doc_categories_docs_legacy_enabled:
    default: false
  doc_categories_simple_mode:
    default: false
    hidden: true
    client: true
    upcoming_change:
      status: "experimental"
      impact: "other,all_members"
  doc_categories_index_editor:
    default: false
    hidden: true
    client: true
    upcoming_change:
      status: "experimental"
      impact: "feature,staff"
  doc_categories_homepage:
    default: ""
    client: true
